### ISSUE TITLE
spark-xml fails to load xml with certain comments

### ISSUE THREAD

**Issue by tlpinney** [databricks/spark-xml#100]
[Sample document](https://repo1.maven.org/maven2/ae/teletronics/godfather/0.9/godfather-0.9.pom)

Removing the comment 

```
<!-- just for information: not inherited in child poms -->
```
allows it to load the xml file into a dataframe.

I am running the master branch of spark-xml with Spark 1.6.0 and Scala 2.10

```xml

<?xml version="1.0" encoding="UTF-8"?>

<!--
Inspired by
* groupId: org.apache, artifactId: apache, version: 15
* http://central.sonatype.org/pages/apache-maven.html

Probably want to extend with inspiration from https://github.com/kevinsawicki/github-maven-example/blob/master/example/pom.xml
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>ae.teletronics</groupId>
  <artifactId>godfather</artifactId>
  <version>0.9</version>
  <packaging>pom</packaging>

  <name>teletronics.ae</name>
  <description>Maven parent for all teletronics.ae open-source</description>
  <url>http://www.teletronics.ae</url>
  <organization>
    <name>teletronics.ae</name>
    <url>http://www.teletronics.ae</url>
  </organization>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <!-- mailingLists>
  </mailingLists -->

  <prerequisites><!-- just for information: not inherited in child poms -->
    <maven>2.2.1</maven><!-- prerequisite of some plugins -->
  </prerequisites>

  <scm>
    <url>https://github.com/TeletronicsDotAe/maven-cross-organization</url>
    <connection>scm:git:git://github.com/TeletronicsDotAe/maven-cross-organization.git</connection>
    <developerConnection>scm:git:git://github.com/TeletronicsDotAe/maven-cross-organization.git</developerConnection>
  </scm>
  
  <developers>
    <developer>
      <email>open-source@teletronics.ae</email>
      <name>Teletronics UAE Open-Source</name>
      <url>https://github.com/TeletronicsDotAe</url>
      <id>open-source-teletronics.ae</id>
    </developer>
  </developers>

  <distributionManagement>
    <snapshotRepository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </snapshotRepository>
    <repository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
    </repository>
  </distributionManagement>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <!-- sourceReleaseAssemblyDescriptor>source-release</sourceReleaseAssemblyDescriptor>
    <organization.logo>http://www.apache.org/images/asf_logo_wide.gif</organization.logo>
    <gpg.useagent>true</gpg.useagent>
    <arguments />
    <!- Specify the default compiler source/target as 1.4 for backwards compatibility
    <maven.compiler.source>1.4</maven.compiler.source>
    <maven.compiler.target>1.4</maven.compiler.target -->    
  </properties>

  <build>
  </build>

  <profiles>
    <profile> 
      <id>release</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <version>2.2.1</version>
            <executions>
              <execution>
                <id>attach-sources</id>
                <goals>
                  <goal>jar-no-fork</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <version>2.9.1</version>
            <executions>
              <execution>
                <id>attach-javadocs</id>
                <goals>
                  <goal>jar</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>1.5</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-release-plugin</artifactId>
            <version>2.5</version>
            <configuration>
              <autoVersionSubmodules>true</autoVersionSubmodules>
              <useReleaseProfile>false</useReleaseProfile>
              <releaseProfiles>release</releaseProfiles>
              <goals>deploy</goals>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.sonatype.plugins</groupId>
            <artifactId>nexus-staging-maven-plugin</artifactId>
            <version>1.6.3</version>
            <extensions>true</extensions>
            <configuration>
               <serverId>ossrh</serverId>
               <nexusUrl>https://oss.sonatype.org/</nexusUrl>
               <autoReleaseAfterClose>true</autoReleaseAfterClose>
            </configuration>
          </plugin>      
        </plugins>
      </build>
    </profile>
  </profiles>
</project>


```

Stack Trace
```
scala> val df = sqlContext.read.format("com.databricks.spark.xml").option("rowTag","project").load("godfather-0.9.pom")
16/03/08 09:45:45 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.RuntimeException: Failed to parse data with unexpected event <!-- just for information: not inherited in child poms -->
	at scala.sys.package$.error(package.scala:27)
	at com.databricks.spark.xml.util.InferSchema$.inferField(InferSchema.scala:144)
	at com.databricks.spark.xml.util.InferSchema$.com$databricks$spark$xml$util$InferSchema$$inferObject(InferSchema.scala:170)
	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:94)
	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:83)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1121)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1121)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1122)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1122)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
...
```

Schema after the comment is removed 
```
scala> df.printSchema
root
 |-- @schemaLocation: string (nullable = true)
 |-- @xmlns: string (nullable = true)
 |-- @xsi: string (nullable = true)
 |-- artifactId: string (nullable = true)
 |-- build: string (nullable = true)
 |-- description: string (nullable = true)
 |-- developers: struct (nullable = true)
 |    |-- developer: struct (nullable = true)
 |    |    |-- email: string (nullable = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- name: string (nullable = true)
 |    |    |-- url: string (nullable = true)
 |-- distributionManagement: struct (nullable = true)
 |    |-- repository: struct (nullable = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- url: string (nullable = true)
 |    |-- snapshotRepository: struct (nullable = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- url: string (nullable = true)
 |-- groupId: string (nullable = true)
 |-- licenses: struct (nullable = true)
 |    |-- license: struct (nullable = true)
 |    |    |-- distribution: string (nullable = true)
 |    |    |-- name: string (nullable = true)
 |    |    |-- url: string (nullable = true)
 |-- modelVersion: string (nullable = true)
 |-- name: string (nullable = true)
 |-- organization: struct (nullable = true)
 |    |-- name: string (nullable = true)
 |    |-- url: string (nullable = true)
 |-- packaging: string (nullable = true)
 |-- prerequisites: struct (nullable = true)
 |    |-- maven: string (nullable = true)
 |-- profiles: struct (nullable = true)
 |    |-- profile: struct (nullable = true)
 |    |    |-- build: struct (nullable = true)
 |    |    |    |-- plugins: struct (nullable = true)
 |    |    |    |    |-- plugin: array (nullable = true)
 |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |-- artifactId: string (nullable = true)
 |    |    |    |    |    |    |-- configuration: struct (nullable = true)
 |    |    |    |    |    |    |    |-- autoReleaseAfterClose: boolean (nullable = true)
 |    |    |    |    |    |    |    |-- autoVersionSubmodules: boolean (nullable = true)
 |    |    |    |    |    |    |    |-- goals: string (nullable = true)
 |    |    |    |    |    |    |    |-- nexusUrl: string (nullable = true)
 |    |    |    |    |    |    |    |-- releaseProfiles: string (nullable = true)
 |    |    |    |    |    |    |    |-- serverId: string (nullable = true)
 |    |    |    |    |    |    |    |-- useReleaseProfile: boolean (nullable = true)
 |    |    |    |    |    |    |-- executions: struct (nullable = true)
 |    |    |    |    |    |    |    |-- execution: struct (nullable = true)
 |    |    |    |    |    |    |    |    |-- goals: struct (nullable = true)
 |    |    |    |    |    |    |    |    |    |-- goal: string (nullable = true)
 |    |    |    |    |    |    |    |    |-- id: string (nullable = true)
 |    |    |    |    |    |    |    |    |-- phase: string (nullable = true)
 |    |    |    |    |    |    |-- extensions: boolean (nullable = true)
 |    |    |    |    |    |    |-- groupId: string (nullable = true)
 |    |    |    |    |    |    |-- version: string (nullable = true)
 |    |    |-- id: string (nullable = true)
 |-- properties: struct (nullable = true)
 |    |-- project.build.sourceEncoding: string (nullable = true)
 |    |-- project.reporting.outputEncoding: string (nullable = true)
 |-- scm: struct (nullable = true)
 |    |-- connection: string (nullable = true)
 |    |-- developerConnection: string (nullable = true)
 |    |-- url: string (nullable = true)
 |-- url: string (nullable = true)
 |-- version: double (nullable = true)
```

**Comment by tlpinney** [comment]
Simplified version of xml which causes an error.

```xml
<project>
  <foo><!-- comment --></foo>
</project>
```

This will be loaded correctly
```xml
<project>
  <foo>bar<!-- comment --></foo>
</project>
```

**Comment by HyukjinKwon** [comment]
@tlpinney Yea, this is an issue. I forgot to document this. Thanks!

**Comment by HyukjinKwon** [comment]
@tlpinney Actually, this could be done easier than I thought. Thanks for reporting this.

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/databricks/spark-xml/pull/110.

**Comment by HyukjinKwon** [comment]
I am closing this. Feel free to reopen if this is still happening.
