### ISSUE TITLE
MatchError when trying to query XML files with partial attributes

### ISSUE THREAD

**Issue by yawnt** [databricks/spark-xml#108]
Hi,

I have a fairly complex set of XML files that I'd like to load. Schema inference seems to work fine, but I cannot query anything as it fails with "scala.MatchError: 2 (of class java.lang.Long)"

I extracted a small example from my XMLs

1.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<events>
  <event pid="2">10</event>
  <event pid="2">12</event>
  <event pid="2">16</event>
  <event pid="2">17</event>
  <event pid="2">18</event>
</events>
```

2.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<events>
  <event pid="1">7</event>
  <event pid="2">12</event>
  <event pid="2">13</event>
  <event pid="2">14</event>
  <event pid="2" exit="t">14</event>
  <event pid="2">16</event>
  <event pid="2">17</event>
</events>
```

This is what happens when I tried to query it in Spark-Shell

```
scala> val df = sqlContext.read.format("com.databricks.spark.xml").option("rowTag","events").load("/tmp/test_dataset/*.xml")
df: org.apache.spark.sql.DataFrame = [event: array<struct<#VALUE:bigint,@exit:string,@pid:bigint>>]

scala> df.printSchema()
root
 |-- event: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- #VALUE: long (nullable = true)
 |    |    |-- @exit: string (nullable = true)
 |    |    |-- @pid: long (nullable = true)

scala> df.select("event").show()
16/04/04 17:39:51 ERROR Executor: Exception in task 0.0 in stage 37.0 (TID 8903)
scala.MatchError: 2 (of class java.lang.Long)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StringConverter$.toCatalystImpl(CatalystTypeConverters.scala:295)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StringConverter$.toCatalystImpl(CatalystTypeConverters.scala:294)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:102)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:260)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:250)
```

any ideas?
Thanks!!

**Comment by HyukjinKwon** [comment]
Thanks for reporting this!

I think maybe this is related with https://github.com/databricks/spark-xml/pull/89.
I just tested with the data above and it looks it works fine for master branch.
I am going to release 0.3.3, https://github.com/databricks/spark-xml/pull/99. This will solve this problem.

Unfortunately, I have not yet released `0.3.3-SNAPHOST`. So, would you use the one manually built by `sbt/sbt package` at the cloned directory if you are urgent?

**Comment by yawnt** [comment]
I will try compiling from master today and let you know, thanks for the prompt reply and the awesome package!

**Comment by yawnt** [comment]
can confirm it works if I compile from master. I will eagerly await `0.3.3-SNAPSHOT`.

Thanks!
