### ISSUE TITLE
java.lang.ClassNotFoundException: Failed to find data source: 

### ISSUE THREAD

**Issue by archerbj** [databricks/spark-xml#152]
Hi , i am just testing the example code 

```scala 
import com.databricks.spark.xml
val str = "/Users/ArcherMacPro/coding/bigData/resources/books.xml"
val df = sqlContext.read
    .format("com.databricks.spark.xml")
    .option("rowTag", "book")
    .load(str)

```

but i ran into this classNotFoundException 

BTW,  i am using spark 1.6.1 
tried test from spark shell with
  $SPARK_HOME/bin/spark-shell --packages com.databricks:spark-xml_2.11:0.3.3

java.lang.ClassNotFoundException: Failed to find data source: /Users/ArcherMacPro/coding/bigData/resources/books.xml. Please find packages at http://spark-packages.org
       	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:77)
       	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:102)
       	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
       	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:109)
       	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:29)
       	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:34)
       	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:36)
       	at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:38)
       	at $iwC$$iwC$$iwC$$iwC.<init>(<console>:40)
       	at $iwC$$iwC$$iwC.<init>(<console>:42)
       	at $iwC$$iwC.<init>(<console>:44)
       	at $iwC.<init>(<console>:46)
       	at <init>(<console>:48)
       	at .<init>(<console>:52)
       	at .<clinit>(<console>)
       	at .<init>(<console>:7)
       	at .<clinit>(<console>)
       	at $print(<console>)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
       	at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1346)
       	at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
       	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
       	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
       	at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
       	at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
       	at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
       	at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
       	at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
       	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
       	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
       	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
       	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
       	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
       	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
       	at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1059)
       	at org.apache.spark.repl.Main$.main(Main.scala:31)
       	at org.apache.spark.repl.Main.main(Main.scala)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
       	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
       	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
       	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
       	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: /Users/ArcherMacPro/coding/bigData/resources/books.xml.DefaultSource
       	at scala.tools.nsc.interpreter.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:83)
       	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4$$anonfun$apply$1.apply(ResolvedDataSource.scala:62)
       	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4$$anonfun$apply$1.apply(ResolvedDataSource.scala:62)
       	at scala.util.Try$.apply(Try.scala:161)
       	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4.apply(ResolvedDataSource.scala:62)
       	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4.apply(ResolvedDataSource.scala:62)
       	at scala.util.Try.orElse(Try.scala:82)
       	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:62)
       	... 49 more

**Comment by HyukjinKwon** [comment]
Hm.. so you mean 

```
$SPARK_HOME/bin/spark-shell --packages com.databricks:spark-xml_2.11:0.3.3
```

or 

```
$SPARK_HOME/bin/spark-shell --packages com.databricks:spark-xml_2.10:0.3.3
```

is not working in 1.6.1?

**Comment by archerbj** [comment]
```
$SPARK_HOME/bin/spark-shell --packages com.databricks:spark-xml_2.10:0.3.3
```

works in spark 1.6.1  

```
$SPARK_HOME/bin/spark-shell --packages com.databricks:spark-xml_2.11:0.3.3
``` 
dosen't work  

this is so weird  lol

**Comment by HyukjinKwon** [comment]
Ah, you should match the Scala version to the one of Spark one. That's why there is two versions of complied libraryies here :). Please let me close this. If you feel strongly this is an issue, please reopen this!

**Comment by amolgawaligithub** [comment]
You have to set spark home directory to solve this issue. Simply you can use System.setProperty("spark.home.dir", "D:\\Amol\\SparkML\\spark-2.4.3-bin-hadoop2.7");
