### ISSUE TITLE
Failed to parse a value for data type StructType

### ISSUE THREAD

**Issue by anayyar82** [databricks/spark-xml#157]
While reading XML file containing multiple rows, getting below error  : any way we can disable the validation check .

Caused by: java.lang.RuntimeException: Failed to parse a value for data type StructType(StructField(Ref,LongType,true), StructField(_VALUE,StringType,true)).
    at scala.sys.package$.error(package.scala:27)
    at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$com$databricks$spark$xml$parsers$StaxXmlParser$$convertTo$1.apply(StaxXmlParser.scala:140)
    at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$com$databricks$spark$xml$parsers$StaxXmlParser$$convertTo$1.apply(StaxXmlParser.scala:126)
    at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$convertValues$1$$anonfun$apply$1.apply$mcVI$sp(StaxXmlParser.scala:179)
    at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$convertValues$1$$anonfun$apply$1.apply(StaxXmlParser.scala:177)
    at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$convertValues$1$$anonfun$apply$1.apply(StaxXmlParser.scala:177)
    at scala.Option.foreach(Option.scala:236)

**Comment by HyukjinKwon** [comment]
Do you mind if I ask some codes and sample data maybe?

**Comment by anayyar82** [comment]
It was same which sent you, the xml  and code is same.

**Comment by anayyar82** [comment]
Is it possible for you to reproduce it

**Comment by HyukjinKwon** [comment]
@anayyar82 Sorry for my late reply. Are you still facing this problem? I would like to confirm before trying to reproduce this.

**Comment by shermilaguerra** [comment]
i has same problem.
Failed to parse a value for data type StructType.
i have xml about publications articles. This arquive  has alot parse. 
I read xml file
data = sqlContext.read.format('com.databricks.spark.xml').options(rowTag='ARTIGOSPUBLICADOS').load("file:///home/cloudera/dayse2.XML")

whenever  i to parse a value for data type it fails with exception:
data.select(explode(Data.ARTIGOPUBLICADO)).collect()
cannot resolve 'explode(ARTIGOPUBLICADO)' due to data type mismatch: input to function explode should be array or map type, not StructType(StructField(@ORDEM-IMPORTANCIA,StringType,true), StructField(@SEQUENCIA-PRODUCAO,LongType,true), StructField(AREAS-DO-CONHECIMENTO,StructType(StructField(AREA-DO-CONHECIMENTO-1,StructType(StructField(#VALUE,StringType,true), StructField(@NOME-DA-AREA-DO-CONHECIMENTO,StringType,true), StructField(@NOME-DA-ESPECIALIDADE,StringType,true), StructField(@NOME-DA-SUB-AREA-DO-CONHECIMENTO,StringType,true), StructField(@NOME-GRANDE-AREA-DO-CONHECIMENTO,StringType,true)),true), StructField(AREA-DO-CONHECIMENTO-2,StructType(StructField(#VALUE,StringType,true), StructField(@NOME-DA-AREA-DO-CONHECIMENTO,StringType,true), StructField(@NOME-DA-ESPECIALIDADE,StringType,true), StructField(@NOME-DA-SUB-AREA-DO-CONHECIMENTO,StringType,true)....

the exeption is:
 cannot resolve 'explode(ARTIGOPUBLICADO)' due to data type mismatch: input to function explode should be array or map type, not StructType

**Comment by hariramesh9a** [comment]
Is this issue resolved? I had a similar issue and got it resolved .. it seems I was trying to explode struct of arrays..

**Comment by srowen** [comment]
The initial issue is cause by invalid data. Set PERMISSIVE mode? The second issue is a problem in the caller's Spark code.
