### ISSUE TITLE
Trying to use XmlInputFormat in pyspark

### ISSUE THREAD

**Issue by Esteban-De-la-Sexface** [databricks/spark-xml#181]
I am trying to load an XML file using newAPIHadoopFile and it keeps throwing the following error from pyspark context

t com.databricks.spark.xml.XmlRecordReader.initialize(XmlInputFormat.scala:76)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:172)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:130)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:67)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
    at org.apache.spark.scheduler.Task.run(Task.scala:85)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    ... 1 more

I am calling it as follows, Spark 2.0

xml = sc.newAPIHadoopFile(
    ...:     '/path/to/xml',
    ...:     'com.databricks.spark.xml.XmlInputFormat',
    ...:     'org.apache.hadoop.io.LongWritable',
    ...:     'org.apache.hadoop.io.Text',
    ...:     conf={
    ...:         'XmlInputFormat.START_TAG_KEY':'<product>',
    ...:         'XmlInputFormat.END_TAG_KEY':'</product>',
'XmlInputFormat.ENCODING_KEY': 'utf-8'})

any ideas

**Comment by HyukjinKwon** [comment]
Could you try this? (I haven't tried this but I think this should work).

```python
xml = sc.newAPIHadoopFile(
    '/path/to/xml',
    'com.databricks.spark.xml.XmlInputFormat',
    'org.apache.hadoop.io.LongWritable',
    'org.apache.hadoop.io.Text',
    conf={
        'xmlinput.start':'<book>',
        'xmlinput.end':'</book>',
        'xmlinput.encoding': 'utf-8'})
```

**Comment by HyukjinKwon** [comment]
I believe this is rather a Spark problem if it does not work. Let me close this for now. Please feel free to reopen this if you face still this issue.
