### ISSUE TITLE
Path to nested column not found

### ISSUE THREAD

**Issue by someonehere15** [databricks/spark-xml#201]
I'm having an issue and I'm not sure if DataFrames are the problem or spark-xml. If it's a bug then I hope you fix it, otherwise I would really appreciate any help even if spark-xml is not the problem.

So, I have the following XML:
```
<root>
  <path>
    <to>
      <atag>
        <atag_number>1</atag_number>
        <more>
          <again>
            <text>1111</text>
          </again>
        </more>
        <more>
          <again>
            <text>2222</text>
          </again>
        </more>
        <more>
          <again>
            <text>3333</text>
          </again>
        </more>
      </atag>
      <atag>
        <atag_number>2</atag_number>
        <more>
          <again>
            <text>4444</text>
          </again>
        </more>
        <more>
          <again>
            <text>5555</text>
          </again>
        </more>
        <more>
          <again>
            <text>6666</text>
          </again>
        </more>
      </atag>
    </to>
  </path>
</root>
```
and I would like to get a table containing `path.to.atag.more.again.text`. I want them to be atomic, so it would need to be exploded to get a row for each `text` value.

If I select e.g. `path.to.atag[0].more.again.text`, I get a list ['1111','2222','3333'].
But if I want all a tags from the file, so if I select `path.to.atag.more.again.text`, I get an error, saying:

```
Traceback (most recent call last):
  File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\sql\utils.py", line 63, in deco
    return f(*a, **kw)
  File "...\spark-2.0.1-bin-hadoop2.7\python\lib\py4j-0.10.3-src.zip\py4j\protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o34.selectExpr.
: org.apache.spark.sql.AnalysisException: No such struct field text in again; line 1 pos 0

	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.findField(complexTypeExtractors.scala:85)

	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.apply(complexTypeExtractors.scala:58)

	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$3.apply(LogicalPlan.scala:253)

	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$3.apply(LogicalPlan.scala:252)

	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)

	at scala.collection.immutable.List.foldLeft(List.scala:84)

	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolve(LogicalPlan.scala:252)

	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveChildren(LogicalPlan.scala:148)

	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$9$$anonfun$applyOrElse$5$$anonfun$31.apply(Analyzer.scala:604)

	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$9$$anonfun$applyOrElse$5$$anonfun$31.apply(Analyzer.scala:604)

	at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:48)

	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$9$$anonfun$applyOrElse$5.applyOrElse(Analyzer.scala:604)

	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$9$$anonfun$applyOrElse$5.applyOrElse(Analyzer.scala:600)

	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)

	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)

	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)

	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:300)

	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:298)

	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:298)

	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:321)

	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:179)

	at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:319)

	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:298)

	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionUp$1(QueryPlan.scala:191)

	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:201)

	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2$1.apply(QueryPlan.scala:205)

	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)

	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)

	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)

	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)

	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)

	at scala.collection.AbstractTraversable.map(Traversable.scala:104)

	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:205)

	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$5.apply(QueryPlan.scala:210)

	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:179)

	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:210)

	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$9.applyOrElse(Analyzer.scala:600)

	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$$anonfun$apply$9.applyOrElse(Analyzer.scala:542)

	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolveOperators$1.apply(LogicalPlan.scala:61)

	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolveOperators$1.apply(LogicalPlan.scala:61)

	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)

	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:60)

	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.apply(Analyzer.scala:542)

	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveReferences$.apply(Analyzer.scala:479)

	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)

	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)

	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)

	at scala.collection.immutable.List.foldLeft(List.scala:84)

	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)

	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)

	at scala.collection.immutable.List.foreach(List.scala:381)

	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)

	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:65)

	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:63)

	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:51)

	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)

	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:2603)

	at org.apache.spark.sql.Dataset.select(Dataset.scala:969)

	at org.apache.spark.sql.Dataset.selectExpr(Dataset.scala:1004)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)

	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)

	at py4j.Gateway.invoke(Gateway.java:280)

	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)

	at py4j.commands.CallCommand.execute(CallCommand.java:79)

	at py4j.GatewayConnection.run(GatewayConnection.java:214)

	at java.lang.Thread.run(Unknown Source)



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\MyModule.py", line 67, in <module>
    df_output = df.selectExpr('path.to.atag.more.again.text')
  File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\sql\dataframe.py", line 875, in selectExpr
    jdf = self._jdf.selectExpr(self._jseq(expr))
  File "...\spark-2.0.1-bin-hadoop2.7\python\lib\py4j-0.10.3-src.zip\py4j\java_gateway.py", line 1133, in __call__
  File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\sql\utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.AnalysisException: 'No such struct field text in again; line 1 pos 0'
```

**Comment by someonehere15** [comment]
Just adding here that for this structure:
```
<root>
  <tug>
    <x>textX</x>
  </tug>
  <teg>
    <tag>
	  <sup>
        <a>textA1</a>
        <a>textA2</a>
        <b>textB1</b>
	  </sup>
    </tag>
    <tag>
	  <sup>
        <a>textA3</a>
        <b>textB2</b>
	  </sup>
    </tag>
  </teg>
</root>
```
the path teg.tag.sup.a works, and gives me:
`[WrappedArray(textA1, textA2), WrappedArray(textA3)]`
for the two levels of array, in `tag `and `a`. So I don't know why for the code above it doesn't.

In my script, I input the columns dynamically, and need to get a flattened table in the end. So basically, I need to flatten the complete XML file so that I can export to csv. But as I said, I cannot statically do it in the code since the columns are to be dinamically at runtime.

Any chance spark-xml could directly fill a dataframe with a flattened structures and avoid arrays?
Any idea if the issue I posted here is a dataframe or spark-xml problem?
Any help anyway?
THANKS :)

**Comment by HyukjinKwon** [comment]
I guess this is related with https://github.com/databricks/spark-xml#structure-conversion . There is a limitation for converting XML structure to dataframe. Maybe we need to take flattening into account so that users can easily access to the data.

**Comment by someonehere15** [comment]
Hey thanks for answering. So is there any chance to adapt it for flattening, or any way I can do it myself? The script I have implemented relies on dataframes and spark-xml, and I just now discovered that arrays are a problem. So it would really help me it there's any way to solve this. Its just a problem for repeatable tags which create arrays, and not for all the nesting, which can be navigated through the dot operator.

**Comment by someonehere15** [comment]
Just wanted to add here that I added some comments on #203 , subpoint 2, describing a similar issue.

**Comment by someonehere15** [comment]
So, an update:
I wrote the following python function to iterate through the schema and explode the arrays:
```
    def explodePath(dataFrame, pathString, tmpColSeparator='___'):
        path = pathString.split('.')
        isExploded = False
        colExploded = tmpColSeparator.join(['TMP'] + path)
        colNonArray = []
        schemaList = dataFrame.schema
        for i,col in enumerate(path):
            if isinstance(schemaList[col].dataType,ArrayType):
                dataFrame = dataFrame.withColumn(colExploded,explode('.'.join([colExploded] + colNonArray + [col]))) if isExploded == True else dataFrame.withColumn(colExploded,explode('.'.join(path[0:i+1])))
                isExploded = True
                colNonArray = []
                schemaList = dataFrame.schema[colExploded].dataType
            else:
                colNonArray.append(col)
                schemaList = schemaList[col].dataType
        colName = '.'.join([colExploded] + colNonArray) if isExploded == True else pathString
        return dataFrame, colName
```
which only explodes when necessary, otherwise it doesn't change the dataframe. The problem is apparently I get a `heap out of space` error when executing it, even with only one xml file with few entries.

Could you please help me? As I said, if you could add an option to spark-xml to avoid arrays, that would be great. Otherwise, could you please give me a push in the right direction. I can't seem to find any information online for a better solution.

**Comment by HyukjinKwon** [comment]
I took a look. I made the structure conversion limitation https://github.com/databricks/spark-xml#structure-conversion to avoid conflict between DataFrame and XML .. if we get rid of this limitation as an option, it will cause another set of problem (e.g., unable to read/write back). You can manually flatten this via, for instance, `explode`. Let's don't fix it in this library.
