### ISSUE TITLE
Using jar "spark-xml_2.11-0.4.1" with Python Error - org.apache.spark.sql.types.DecimalType$.Unlimited(

### ISSUE THREAD

**Issue by ivaradagit** [databricks/spark-xml#209]
I am using the latest jar code with python. I try to parse the sample xml books.xml but i still run into the error:

: java.lang.NoSuchMethodError: org.apache.spark.sql.types.DecimalType$.Unlimited()Lorg/apache/spark/
sql/types/DecimalType;
        at com.databricks.spark.xml.util.InferSchema$.<init>(InferSchema.scala:50)
        at com.databricks.spark.xml.util.InferSchema$.<clinit>(InferSchema.scala)
        at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:46)
        at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:46)
        at scala.Option.getOrElse(Option.scala:121)
        at com.databricks.spark.xml.XmlRelation.<init>(XmlRelation.scala:45)
        at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:66)
        at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:44)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:33
0)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Unknown Source)

Can you please help!

**Comment by HyukjinKwon** [comment]
It looks you are using Spark lower than 1.6.x? In that case, please try 0.3.4. Please refer https://github.com/databricks/spark-xml#requirements

**Comment by ivaradagit** [comment]
Thank you for the response, i am using spark 2.0.1 (2x).

**Comment by HyukjinKwon** [comment]
Then, it seems lower verion of this library is being referred because in 0.4.1, `Unlimited` is not being used in the line - https://github.com/databricks/spark-xml/blob/v0.4.1/src/main/scala/com/databricks/spark/xml/util/InferSchema.scala#L50

But, this is being used in 0.3.x - https://github.com/databricks/spark-xml/blob/v0.3.5/src/main/scala/com/databricks/spark/xml/util/InferSchema.scala#L50

**Comment by HyukjinKwon** [comment]
I just downloaded the jar source spark-xml_2.11-0.4.1 and then manually checked the codes. It seems old jar is in the path.

**Comment by ivaradagit** [comment]
Thanks again for the super quick response. Will you be able to checkin the new code. I will download it and rebuild it again.

**Comment by ivaradagit** [comment]
Apologize for my earlier response, i did have a bad reference to an old jar 0.3. Thanks again!

**Comment by HyukjinKwon** [comment]
No problem :). Do you mind if I ask to close this issue if it is fine?
