### ISSUE TITLE
Parse row as failed when it contains chars not in defined charset

### ISSUE THREAD

**Issue by tonizzz** [databricks/spark-xml#211]
I got the error below when processing an XML file and only one of the entries had an invalid UTF8 character. The whole DF was failed with exception as below:

```
Job aborted due to stage failure: Task 40 in stage 100.0 failed 4 times, most recent failure: Lost task 40.3 in stage 100.0 (TID 6343, hadoop-38.backend): [com.ctc.wstx.exc.WstxLazyException] com.ctc.wstx.exc.WstxIOException: Invalid UTF-8 character 0xfffe at char #790, byte #-1)
	at com.ctc.wstx.exc.WstxLazyException.throwLazily(WstxLazyException.java:45)
	at com.ctc.wstx.evt.FilteredEventReader.hasNext(FilteredEventReader.java:72)
	at com.databricks.spark.xml.parsers.StaxXmlParserUtils$.skipUntil(StaxXmlParserUtils.scala:14)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$parse$1$$anonfun$apply$4.apply(StaxXmlParser.scala:90)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$parse$1$$anonfun$apply$4.apply(StaxXmlParser.scala:82)
```

I think code below should be changed to add Exception at the end , so any exception happens we don't throw away the whole XML file, but only the affected record:

StaxXmlParser:
```
iter.flatMap { xml =>
        // It does not have to skip for white space, since `XmlInputFormat`
        // always finds the root tag without a heading space.
        val reader = new ByteArrayInputStream(xml.getBytes)
        val eventReader = factory.createXMLEventReader(reader)
        val parser = factory.createFilteredReader(eventReader, filter)
        try {
          val rootEvent =
            StaxXmlParserUtils.skipUntil(parser, XMLStreamConstants.START_ELEMENT)
          val rootAttributes =
            rootEvent.asStartElement.getAttributes.map(_.asInstanceOf[Attribute]).toArray
          Some(convertObject(parser, schema, options, rootAttributes))
            .orElse(failedRecord(xml))
        } catch {
          case _: java.lang.NumberFormatException =>
            failedRecord(xml)
          case _: java.text.ParseException | _: IllegalArgumentException =>
            failedRecord(xml)
          case _: XMLStreamException =>
            failedRecord(xml)
          **case _: Exception =>
            failedRecord(xml)**
        }
      }
```

**Comment by HyukjinKwon** [comment]
I see. Would we able to resemble CSV's way in Spark (https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/csv/CSVRelation.scala#L138) and use

```scala
case NonFatal(e) =>
  ...
```

instead for

```scala
case _: java.lang.NumberFormatException =>
  failedRecord(xml)
case _: java.text.ParseException | _: IllegalArgumentException =>
  failedRecord(xml)
case _: XMLStreamException =>
  failedRecord(xml)
```
?

BTW, there are similar logics `InferSchema` we should fix too.

**Comment by HyukjinKwon** [comment]
Please go ahead and open a PR if you are interested in this and able to do this. It would be great if we check using `NonFatal` is safe ahead to doubly make sure and then leave some notes about this.

**Comment by srowen** [comment]
Looks like this was already done in https://github.com/databricks/spark-xml/pull/261
