### ISSUE TITLE
Error trying to save dataframe

### ISSUE THREAD

**Issue by ravimn** [databricks/spark-xml#225]
Hi,

I have a Hortonworks Hadoop cluster that is running spark v1.6.2 and HDP v2.4.2.  I have an xml file in hdfs which is read successfully using the library.  I am using spark-xml 2.10-0.4.1.  However I am getting an error trying to write the dataframe back to file or hdfs.  

Below is the code I used.

package com.fanniemae.bigDataRecon

import org.apache.spark.SparkContext
import org.apache.spark.SparkContext._
import org.apache.spark.sql.SQLContext
import org.apache.spark.SparkConf
import org.apache.spark.rdd.RDD

/**
 * @author ${user.name}
 */
object App {
  
  def foo(x:Array[String]) = x.foldLeft("")((a,b) => a+b)
  
  def main(args : Array[String]) {
    val sparkConf = new SparkConf().setAppName("Hdfs Test")
    val sc = new SparkContext(sparkConf)
    val sqlContext = new SQLContext(sc)
    
    val df = sqlContext.read
      .format("com.databricks.spark.xml")
      .option("rowTag", "Loan")
      .load("hdfs:///user/myuser/Loan.xml")
      
    df.show()
    
    val sd = df.select("Id", "Date")
    sd.show()
      
    sd.write
      .mode("overwrite")
      .format("com.databricks.spark.xml")
      .option("rootTag","Loans").option("rowTag","Loan")
      .save("/tmp/1.xml")    

  }
}

Below is the command I am running:
/usr/hdp/current/spark-client/bin/spark-submit --class com.fanniemae.bigDataRecon.App --jars /tmp/spark-xml_2.10-0.4.1.jar --master local --num-executors 1 --driver-memory 512m --executor-memory 512m --executor-cores 1 /tmp/err-0.0.1-SNAPSHOT-jar-with-dependencies.jar "hdfs:///user/userId/Loan.xml" "/tmp/1.xml"

Below is the exception I am getting for the save method.  

Exception in thread "main" java.lang.AbstractMethodError: com.databricks.spark.xml.DefaultSource.createRelation(Lorg/apache/spark/sql/SQLContext;Lorg/apache/spark/sql/SaveMode;Lscala/collection/immutable/Map;Lorg/apache/spark/sql/DataFrame;)Lorg/apache/spark/sql/sources/BaseRelation;
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
        at com.fanniemae.bigDataRecon.App$.main(App.scala:37)
        at com.fanniemae.bigDataRecon.App.main(App.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Can you please help.  Not able to understand what the issue is.

**Comment by HyukjinKwon** [comment]
It looks due to version mismatch. Could you try 0.3.x for Spark 1.3.x+?

**Comment by HyukjinKwon** [comment]
Please take a look at https://github.com/databricks/spark-xml/tree/branch-0.3

**Comment by buddingPop** [comment]
I got similar error when working with spark 1.6.0 + spark-xml 2.10-0.4.1
Changing back into spark-xml 2.10-0.3.5 solved this issue for me.

**Comment by srowen** [comment]
You have multiple copies of the library on your classpath. Presumably the other copy is 0.3.5.
