### ISSUE TITLE
More detailed error descriptions for unparsed files

### ISSUE THREAD

**Issue by someonehere15** [databricks/spark-xml#246]
Is it possible to get more detailed descriptions for skipped or unparsed files?

It is as of now possible to get the corrupt column in the parsed DataFrame, or as a log entry if in DROPMALFORMED mode. But if a row is supposed to contain more complex structures (e.g. a directory with XML files and the rowTag is the root tag of each file, which would mean each XML file creates one row in the DF, and this row contains nested structures), then from the "_corrupt_column" column I can only get the problematic content not more granular than the rowTag (which would be a whole file in the example). So I still don't know which tag exactly was the problem inside of the defined rowTag, or what other errors there were.

Is there any way to extract more detailed informations on the actual cause of the problem than just the whole content of the problem row? At least a stack trace or similar should be possible to be retrieved at each moment that an error occurs, instead of simply skipping that row and putting its content in a column. Maybe by adding another column with an error description?

**Comment by Yansongsongsong** [comment]
When I was parsing one xml encoded in `ISO-8859-1`,
the row with special character make some errors
e.g.:
```xml
<article mdate="2017-05-28" key="journals/acta/Schonhage77">
<author>Arnold Sch&ouml;nhage</author>
<title>Schnelle Multiplikation von Polynomen &uuml;ber K&ouml;rpern der Charakteristik 2.</title>
<journal>Acta Inf.</journal>
<volume>7</volume>
<year>1977</year>
<pages>395-398</pages>
<url>db/journals/acta/acta7.html#Schonhage77</url>
<ee>https://doi.org/10.1007/BF00289470</ee>
</article>
```
when i save the dataframe, i get the exception:
```scala
// code
selectedData.write
      .format("com.databricks.spark.xml")
      .option("charset", "ISO-8859-1")
      .option("rootTag", "articles")
      .option("rowTag", "article")
      .save(FILE_NAME + System.currentTimeMillis() + "article.xml")// get exception here
```

```
[ task launch worker for task 1] Utils                          ERROR Aborting task
java.lang.NullPointerException: null
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$apply$4.apply(StaxXmlGenerator.scala:131) ~[spark-xml_2.11-0.4.1.jar:0.4.1]
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$apply$4.apply(StaxXmlGenerator.scala:129) ~[spark-xml_2.11-0.4.1.jar:0.4.1]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.4.jar:?]
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$.apply(StaxXmlGenerator.scala:129) ~[spark-xml_2.11-0.4.1.jar:0.4.1]
	at com.databricks.spark.xml.util.XmlFile$$anonfun$1$$anon$1.next(XmlFile.scala:108) ~[spark-xml_2.11-0.4.1.jar:0.4.1]
	at com.databricks.spark.xml.util.XmlFile$$anonfun$1$$anon$1.next(XmlFile.scala:96) ~[spark-xml_2.11-0.4.1.jar:0.4.1]
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:363) ~[scala-library-2.11.4.jar:?]
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1138) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1371) [spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1145) [spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1125) [spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87) [spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:108) [spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338) [spark-core_2.11-2.2.1.jar:2.2.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[ task launch worker for task 1] Executor                       ERROR Exception in task 0.0 in stage 1.0 (TID 1)
java.lang.NullPointerException: null
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$apply$4.apply(StaxXmlGenerator.scala:131) ~[spark-xml_2.11-0.4.1.jar:0.4.1]
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$apply$4.apply(StaxXmlGenerator.scala:129) ~[spark-xml_2.11-0.4.1.jar:0.4.1]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.4.jar:?]
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$.apply(StaxXmlGenerator.scala:129) ~[spark-xml_2.11-0.4.1.jar:0.4.1]
	at com.databricks.spark.xml.util.XmlFile$$anonfun$1$$anon$1.next(XmlFile.scala:108) ~[spark-xml_2.11-0.4.1.jar:0.4.1]
	at com.databricks.spark.xml.util.XmlFile$$anonfun$1$$anon$1.next(XmlFile.scala:96) ~[spark-xml_2.11-0.4.1.jar:0.4.1]
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:363) ~[scala-library-2.11.4.jar:?]
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1138) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1371) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1145) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1125) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:108) ~[spark-core_2.11-2.2.1.jar:2.2.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338) [spark-core_2.11-2.2.1.jar:2.2.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[          task-result-getter-1] TaskSetManager                 WARN  Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): java.lang.NullPointerException
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$apply$4.apply(StaxXmlGenerator.scala:131)
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$apply$4.apply(StaxXmlGenerator.scala:129)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$.apply(StaxXmlGenerator.scala:129)
	at com.databricks.spark.xml.util.XmlFile$$anonfun$1$$anon$1.next(XmlFile.scala:108)
	at com.databricks.spark.xml.util.XmlFile$$anonfun$1$$anon$1.next(XmlFile.scala:96)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:363)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1138)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1371)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1145)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1125)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[          task-result-getter-1] TaskSetManager                 ERROR Task 0 in stage 1.0 failed 1 times; aborting job
[          task-result-getter-1] TaskSchedulerImpl              INFO  Removed TaskSet 1.0, whose tasks have all completed, from pool 
[      dag-scheduler-event-loop] TaskSchedulerImpl              INFO  Cancelling stage 1
[      dag-scheduler-event-loop] DAGScheduler                   INFO  ResultStage 1 (saveAsTextFile at XmlFile.scala:139) failed in 0.299 s due to Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): java.lang.NullPointerException
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$apply$4.apply(StaxXmlGenerator.scala:131)
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$apply$4.apply(StaxXmlGenerator.scala:129)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$.apply(StaxXmlGenerator.scala:129)
	at com.databricks.spark.xml.util.XmlFile$$anonfun$1$$anon$1.next(XmlFile.scala:108)
	at com.databricks.spark.xml.util.XmlFile$$anonfun$1$$anon$1.next(XmlFile.scala:96)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:363)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1138)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1371)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1145)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1125)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by srowen** [comment]
In FAILFAST mode you get the exception that caused parsing to fail as a log message. For example if you run the current unit tests you'll see ...

```
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[6,7]
Message: The element type "model" must be terminated by the matching end-tag "</model>".
```

We could maybe add the same stack trace as a debug level message in PERMISSIVE and DROPMALFORMED mode? so that this would be optionally available to diagnose data problems from the logs. I'm not as sure if it's helpful to put a stack trace in a new column in PERMISSIVE mode.
