### ISSUE TITLE
 java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by BramhaAelem** [databricks/spark-xml#263]
Hi 

I am processing 3GB XML using databricks utility through pyspark.  Job is getting failed with the below error. can you please let me know the recommendations to overcome with the  below error while processing data frame.
  File "oozie_xml_pyspark_job.py", line 21, in <module>
    df = sqlContext.read.format('com.databricks.spark.xml').options(rowTag=rowTag).load(hdfsPath)
  File "/nyl/hadoop/diskc/hadoop/yarn/local/usercache/hdpdevedmingest/appcache/application_1499712243940_3836/container_e178_1499712243940_3836_01_000001/pyspark.zip/pyspark/sql/readwriter.py", line 137, in load
  File "/nyl/hadoop/diskc/hadoop/yarn/local/usercache/hdpdevedmingest/appcache/application_1499712243940_3836/container_e178_1499712243940_3836_01_000001/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/nyl/hadoop/diskc/hadoop/yarn/local/usercache/hdpdevedmingest/appcache/application_1499712243940_3836/container_e178_1499712243940_3836_01_000001/pyspark.zip/pyspark/sql/utils.py", line 45, in deco
  File "/nyl/hadoop/diskc/hadoop/yarn/local/usercache/hdpdevedmingest/appcache/application_1499712243940_3836/container_e178_1499712243940_3836_01_000001/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o44.load.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 27, ha20t5003dn.tech.hdp.newyorklife.com): java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:135)
	at java.io.DataOutputStream.write(DataOutputStream.java:88)
	at com.databricks.spark.xml.XmlRecordReader.readUntilMatch(XmlInputFormat.scala:130)
	at com.databricks.spark.xml.XmlRecordReader.next(XmlInputFormat.scala:99)
	at com.databricks.spark.xml.XmlRecordReader.nextKeyValue(XmlInputFormat.scala:84)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:168)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1142)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1142)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$25.apply(RDD.scala:1143)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$25.apply(RDD.scala:1143)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$22.apply(RDD.scala:717)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$22.apply(RDD.scala:717)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:313)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:277)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:313)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:277)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1433)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1421)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1420)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1420)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:801)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:801)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:801)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1642)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1601)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1590)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:622)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1856)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1976)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1032)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:323)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1014)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1.apply(RDD.scala:1157)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:323)
	at org.apache.spark.rdd.RDD.treeAggregate(RDD.scala:1134)
	at com.databricks.spark.xml.util.InferSchema$.infer(InferSchema.scala:60)
	at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:52)
	at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:52)
	at scala.Option.getOrElse(Option.scala:120)
	at com.databricks.spark.xml.XmlRelation.<init>(XmlRelation.scala:51)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:89)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:43)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:135)
	at java.io.DataOutputStream.write(DataOutputStream.java:88)
	at com.databricks.spark.xml.XmlRecordReader.readUntilMatch(XmlInputFormat.scala:130)
	at com.databricks.spark.xml.XmlRecordReader.next(XmlInputFormat.scala:99)
	at com.databricks.spark.xml.XmlRecordReader.nextKeyValue(XmlInputFormat.scala:84)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:168)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1142)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1142)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$25.apply(RDD.scala:1143)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$25.apply(RDD.scala:1143)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$22.apply(RDD.scala:717)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$22.apply(RDD.scala:717)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:313)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:277)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:313)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:277)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)

**Comment by HyukjinKwon** [comment]
Dose maybe the XML file have a single or few huge records?

**Comment by BramhaAelem** [comment]
XML having huge xml elements with nested structure under single root tag.

example:

<ROOT>
 <A>blah </A>
.
.
.
</ROOT>

**Comment by HyukjinKwon** [comment]
Few huge records will probably cause OOM as at least each record should be able to be loaded and parsed in single JVM. I think you should set the `rootTag` for the narrower elements.

**Comment by HyukjinKwon** [comment]
I don't think we can fix this essentially within this library. I will close this for now. Will probably try to look around these codes and see if there are some places where I can optimize this soon.

**Comment by BramhaAelem** [comment]
How to set rootTag for narrower elements

**Comment by HyukjinKwon** [comment]
For example, setting `A` instead of `ROOT` above. Will probably think about this problem too.

**Comment by BramhaAelem** [comment]
As per my requirement I should store all the elements as such it present in
XML. Because under root I have a keyvalue  for all nested sections. Current
data bricks utility doesn't support to add key element to all nested
sections to identify the records for same key.

**Comment by yechao2016** [comment]
I have the same issue.does it get solved?

**Comment by BramhaAelem** [comment]
No. I have move forward without this saprk-xml utility.  I wrote Xquery
specs to transform data into user acceptable format and loaded into hive.

**Comment by Tagar** [comment]
@HyukjinKwon one of our customers has brought this issue up. 
Support case 00089557 .
Yes they are reading larger xml files / records. 
Not sure if there is a workaround. 
Thanks!

**Comment by srowen** [comment]
I can take support for this library @Tagar . But any customer-facing info should be internal.
I don't think there is a workaround here - the caller is asking it to read huge XML records and needs to have enough memory to do so. Add memory or reevaluate whether the rowTag can be some smaller subset of the XML.

**Comment by Tagar** [comment]
Thank you @srowen - I sent email on this with more details.

**Comment by srowen** [comment]
@Tagar reminds me that the error is actually "Requested array size exceeds VM limit", which actually indicates an array growing too large. So this is actually about a single row tag that is extremely large, more than 2^31 - 1 characters. That's hard to handle without some moderate surgery throughout the code; we'd have to return potentially arrays of smaller strings and adapt everything downstream from the XmlInputFormat to parse XML broken across strings. It seems _possible_ but would be some non-trivial surgery.
