### ISSUE TITLE
xml import failing when using spark-xml and spark-2.2.0-bin-hadoop2.7

### ISSUE THREAD

**Issue by ritikam2** [databricks/spark-xml#270]
I am importing an xml file and I get

java.lang.NoSuchMethodError: org.apache.spark.sql.types.DecimalType$.Unlimited()Lorg/apache/spark/sql/types/DecimalType;
	at com.databricks.spark.xml.util.InferSchema$.<init>(InferSchema.scala:50)
	at com.databricks.spark.xml.util.InferSchema$.<clinit>(InferSchema.scala)
	at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:46)
	at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:46)
	at scala.Option.getOrElse(Option.scala:121)
	at com.databricks.spark.xml.XmlRelation.<init>(XmlRelation.scala:45)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:65)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:43)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:306)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:156)
	
The code that  I run is

Dataset<Row> peopleRDD = spark.read().format("com.databricks.spark.xml").option("rowTag", "dc:Document").load(dirPath);

spark-xml I got is 

<dependency>
    <groupId>com.databricks</groupId>
    <artifactId>spark-xml_2.11</artifactId>
    <version>0.3.1</version>

**Comment by HyukjinKwon** [comment]
Can you try 0.4.0? That's for 2.0.0+.

**Comment by gilcu2** [comment]
I am using 0.4.1 and in 

val sqlContext = new SQLContext(sc)
val df = sqlContext.read
      .format("com.databricks.spark.xml")
      .option("rowTag", "book")
      .xml("books.xml")

I get:

Error:(37, 8) value xml is not a member of org.apache.spark.sql.DataFrameReader
possible cause: maybe a semicolon is missing before `value xml'?
      .xml("books.xml")

**Comment by HyukjinKwon** [comment]
Oh, `.xml("books.xml")` API is not yet released. Please refer the page here:https://github.com/databricks/spark-xml/tree/v0.4.1

**Comment by gilcu2** [comment]
https://mvnrepository.com/artifact/com.databricks/spark-xml_2.11/0.4.1

**Comment by ritikam2** [comment]
Thanks, I relaised later that I need 0.4.0
