### ISSUE TITLE
Save as table operation is failing when child element node contains special character

### ISSUE THREAD

**Issue by abhijeetbedagkar** [databricks/spark-xml#304]
Hi,

I have below xml which I am trying to read through SPARK XML

```
<revolt>
<revolt_configuration>
	<id>102</id>
    <testvalidationcontroller>
        <validation_method>SPARK</validation_method>
        <validation-timeout>5</validation-timeout>
    </testvalidationcontroller>
</revolt_configuration>
</revolt>
```
Please note field 'validation-timeout' under  testvalidationcontroller

I am using below code to read the xml

```
df = spark.read.format('com.databricks.spark.xml').option('rowTag','revolt_configuration').load('/user/configuration.xml')
```

and after doing df.printSchema() I get below output

```
root
 |-- id: long (nullable = true)
 |-- testvalidationcontroller: struct (nullable = true)
 |    |-- validation-timeout: long (nullable = true)
 |    |-- validation_method: string (nullable = true)
 ```

While trying to save this data frame to hive table, I am getting below exception

```
Caused by: java.lang.IllegalArgumentException: Error: : expected at the position 24 of 'bigint:struct<validation-timeout:bigint,validation_method:string>' but '-' is found.
        at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.expect(TypeInfoUtils.java:360)
        at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.expect(TypeInfoUtils.java:331)
        at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.parseType(TypeInfoUtils.java:483)
        at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.parseTypeInfos(TypeInfoUtils.java:305)
        at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils.getTypeInfosFromTypeString(TypeInfoUtils.java:765)
        at org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe.initialize(ParquetHiveSerDe.java:111)
        at org.apache.hadoop.hive.serde2.AbstractSerDe.initialize(AbstractSerDe.java:53)
        at org.apache.hadoop.hive.serde2.SerDeUtils.initializeSerDe(SerDeUtils.java:521)
        at org.apache.hadoop.hive.metastore.MetaStoreUtils.getDeserializer(MetaStoreUtils.java:391)
        at org.apache.hadoop.hive.ql.metadata.Table.getDeserializerFromMetaStore(Table.java:276)
        at org.apache.hadoop.hive.ql.metadata.Table.checkValidity(Table.java:197)
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:699)
        ... 44 more
```
		
If the data does not contain any special chars then save as table operation works correctly. 	
Kindly assist me in this

Thanks,
Abhijeet

**Comment by andrewbanchich** [comment]
I am new to Spark, but I think I'm having a similar issue. I have:

```
val test = sqlContext.read
.format("com.databricks.spark.xml")
.option("rowTag", "XMLNodeName")
.load(s"/file/path/test_file.XML")

display(test)
```

and the output column name is `_corrupt_record`. If I first strip the HTML entity from that `XMLNodeName` then it has no issues.

**Comment by srowen** [comment]
Yes, that's apparently not a valid character in a DB column name in most DBs, including Hive. You need to rename the column before saving. This isn't related to spark-xml per se.
