### ISSUE TITLE
Job aborting with java.util.NoSuchElementException on a large dataset

### ISSUE THREAD

**Issue by royatdb** [databricks/spark-xml#311]
Using: `spark-xml_2.11-0.4.1`

I can't pin point what's the exact XML document that causes following error yet however, I am guessing this is similar to CDATA causing `NoSuchElementException`. 

Following is the stack trace:
```
18/06/15 20:55:18 INFO DAGScheduler: ShuffleMapStage 0 (count at NativeMethodAccessorImpl.java:0) failed in 333.902 s due to Job aborted due to stage failure: Task 61557 in stage 0.0 failed 4 times, most recent failure: Lost task 61557.3 in stage 0.0 (TID 61737, 10.139.64.9, executor 13): java.util.NoSuchElementException
	at com.sun.xml.internal.stream.EventFilterSupport.nextEvent(EventFilterSupport.java:79)
	at com.databricks.spark.xml.parsers.StaxXmlParserUtils$.checkEndElement(StaxXmlParserUtils.scala:31)
	at com.databricks.spark.xml.parsers.StaxXmlParser$.com$databricks$spark$xml$parsers$StaxXmlParser$$convertObject(StaxXmlParser.scala:304)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$parse$1$$anonfun$apply$4.apply(StaxXmlParser.scala:84)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$parse$1$$anonfun$apply$4.apply(StaxXmlParser.scala:73)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithoutKey$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:620)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:111)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

While i try to find the exact XML (it is hidden inside a humongous dataset) that caused this, any suggestions looking at `StaxXmlParserUtils.scala:31` ?

**Comment by BioQwer** [comment]
@royatdb hello
can you show few elements for xml?

**Comment by punithmailme** [comment]
hi @royatdb i am facing an issue where i cannot generate a xml with spark 2.1.2 and spark-xml 0.4.1.. when i run it as a main program i can generate it. but when i submit it as a spark job it fails with XMLStreamException... Can you please help. Here is the sample code https://github.com/punithmailme/spark-xml-new

**Comment by srowen** [comment]
It looks like malformed XML somewhere, yes. It's hard to say how else to find it. Can you break down the data set into halves?
