### ISSUE TITLE
Spark 2.3.1 on Hadoop 3.1.1 Supported?

### ISSUE THREAD

**Issue by Nicbyte** [databricks/spark-xml#379]
Hi 

I'm not sure if spark-xml is supposed to be supported on spark >2.3 builds and hadoop >3.0 yet but getting the error below. Close if not supported yet, this was just "RnD" on a new ecosystem. 

This works perfectly on my hdp 2.6.4 sandbox environment, I tried my luck on a newer build I use for kubernetes and I got the error below when using the latest 0.5.0 build on spark 2.3.1 and hadoop 3.1.1. 

>>> from pyspark.sql import SparkSession
>>> spark = SparkSession.builder.getOrCreate()
>>> df = spark.read.format('xml').options(rowTag='book').load('/user/root/Sample_Data/books.xml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/spark-2.3.1/python/pyspark/sql/readwriter.py", line 166, in load
    return self._df(self._jreader.load(path))
  File "/opt/spark-2.3.1/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/spark-2.3.1/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/opt/spark-2.3.1/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o73.load.
: java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider com.databricks.spark.xml.DefaultSource not a subtype
        at java.util.ServiceLoader.fail(ServiceLoader.java:239)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
        at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
        at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:614)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:190)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)

**Comment by srowen** [comment]
It works fine on Spark 2.4 and should work on Spark 3. I recall a different problem with Hadoop 2.9+: https://github.com/databricks/spark-xml/issues/338 This one I have not seen, and I note that even Spark doesn't necessarily work with Hadoop 3 now. I'm not sure why Hadoop 3 would cause this particular type of error, but I think it handles classloaders differently, which could cause this (DefaultSource does actually implement the interface it says it doesn't). Don't know of any workaround except that you won't want to use Hadoop 3 until Spark supports it, maybe in Spark 3.

**Comment by HyukjinKwon** [comment]
Spark itself does not officially support Hadoop 3 yet.

**Comment by srowen** [comment]
Hm, not sure what to make of that. At least, the tests all pass with Spark 2.3.x here. Is there perhaps some env issue? maybe it's not using the version of Hadoop you think? I'd stick to whatever is in the Spark distribution to be sure.

**Comment by Nicbyte** [comment]
> Hm, not sure what to make of that. At least, the tests all pass with Spark 2.3.x here. Is there perhaps some env issue? maybe it's not using the version of Hadoop you think? I'd stick to whatever is in the Spark distribution to be sure.

Yeah I'm sure this would be something with my environment. I can confirm hadoop is running on 2.7.3, re-formatted namenode etc.  With only spark 2.3.1 and hadoop 2.7.3 the configuration is quite minimal, possibly some required config I have not set.

**Comment by stevenmanton** [comment]
FYI I had this issue and traced the cause to having two different versions of the JAR on the class path (e.g. `spark-xml_2.11-1.0.4.jar` and `spark-xml_2.11-1.0.6.jar`).
