### ISSUE TITLE
Error generated from pyspark while reading an XML file

### ISSUE THREAD

**Issue by azhart** [databricks/spark-xml#460]
I’ve a jupyter notebook reading an xml file thru pyspark. While reading the below line, error message is generated
spark = SparkSession \
            .builder \
            .appName("Create_csv_2_Parquet") \
            .enableHiveSupport() \
            .config('spark.jars', 'spark-xml_2.11-0.6.0.jar') \
            .getOrCreate()

df = spark.read.format('com.databricks.spark.xml').options(rowTag='book',  mode='FAILFAST').load('book.xml')

Py4JJavaError: An error occurred while calling o762.load.
: java.lang.NoClassDefFoundError: Could not initialize class com.databricks.spark.xml.util.PermissiveMode$
	at com.databricks.spark.xml.util.ParseMode$.fromString(ParseMode.scala:52)
	at com.databricks.spark.xml.XmlOptions.<init>(XmlOptions.scala:53)
	at com.databricks.spark.xml.XmlOptions$.apply(XmlOptions.scala:65)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:66)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:52)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:339)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:279)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:268)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:268)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:835)

I would appreciate if anyone can help me here.
Thanks

**Comment by srowen** [comment]
First, I'd use the latest version, 0.9.0.
You have either conflicting versions of spark-xml on the classpath, or else you are using a Scala 2.11 artifact but running on Scala 2.12.

**Comment by azhart** [comment]
@srowen :- Even I'd tried spark-xml_2.12-0.9.0.jar & the outcome is same

Little more context to this issue
Python version: 3.8
Spark version: 3.0.0 (running from windows. Local to my pc)
Spark bin folder has few "scala" jars with 2.12_xx version & this indicates Scala 2.12 is being used.

**Comment by srowen** [comment]
Somewhere you do have an environment issue here, like multiple versions of Spark XML. I can't reproduce this, as the class definitely exists. Yes, 3.0 requires scala 2.12. Is there more to the error?

**Comment by azhart** [comment]
I'd changed the JAR file to 0.9.0 & restarted the pc, executed the same code. This time different error message generated as below

Py4JJavaError: An error occurred while calling o86.load.
: java.lang.NoClassDefFoundError: scala/Product$class
	at com.databricks.spark.xml.util.PermissiveMode$.<init>(ParseMode.scala:33)
	at com.databricks.spark.xml.util.PermissiveMode$.<clinit>(ParseMode.scala)
	at com.databricks.spark.xml.util.ParseMode$.fromString(ParseMode.scala:52)
	at com.databricks.spark.xml.XmlOptions.<init>(XmlOptions.scala:53)
	at com.databricks.spark.xml.XmlOptions$.apply(XmlOptions.scala:65)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:66)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:52)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:339)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:279)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:268)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:268)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

**Comment by srowen** [comment]
That is a scala version mismatch issue. Hard to say why, other than maybe you are not running the copy of spark or spark-xml you think?

**Comment by azhart** [comment]
spark or spark-xml  is running locally.

**Comment by srowen** [comment]
If you are using a 2.11 JAR, that's the problem.
