### ISSUE TITLE
Not able to access xml files from s3

### ISSUE THREAD

**Issue by pankajwynk** [databricks/spark-xml#461]
IDE : Zeppelin Notebook

val sitemapRoot = "s3://music-dev/sitemap"

val df = sqlContext.read.format("com.databricks.spark.xml")
     .option("rowTag", "url")
     .load(s"$sitemapRoot/song*")

package : com.databricks:spark-xml_2.11:0.9.0

Exception ::
>`java.io.IOException: No FileSystem for scheme: s3
  at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
  at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.setInputPaths(FileInputFormat.java:500)
  at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.setInputPaths(FileInputFormat.java:469)
  at org.apache.spark.SparkContext$$anonfun$newAPIHadoopFile$2.apply(SparkContext.scala:1158)
  at org.apache.spark.SparkContext$$anonfun$newAPIHadoopFile$2.apply(SparkContext.scala:1146)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.SparkContext.withScope(SparkContext.scala:699)
  at org.apache.spark.SparkContext.newAPIHadoopFile(SparkContext.scala:1146)
  at com.databricks.spark.xml.util.XmlFile$.withCharset(XmlFile.scala:46)
  at com.databricks.spark.xml.DefaultSource$$anonfun$createRelation$1.apply(DefaultSource.scala:71)
  at com.databricks.spark.xml.DefaultSource$$anonfun$createRelation$1.apply(DefaultSource.scala:71)
  at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:43)
  at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:42)
  at scala.Option.getOrElse(Option.scala:121)
  at com.databricks.spark.xml.XmlRelation.<init>(XmlRelation.scala:41)
  at com.databricks.spark.xml.XmlRelation$.apply(XmlRelation.scala:29)
  at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:74)
  at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:52)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  ... 45 elided`

Then i have added :: **org.apache.hadoop:hadoop-aws:2.7.6**

`java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$
  at org.apache.spark.SparkContext.withScope(SparkContext.scala:699)
  at org.apache.spark.SparkContext.newAPIHadoopFile(SparkContext.scala:1146)
  at com.databricks.spark.xml.util.XmlFile$.withCharset(XmlFile.scala:46)
  at com.databricks.spark.xml.DefaultSource$$anonfun$createRelation$1.apply(DefaultSource.scala:71)
  at com.databricks.spark.xml.DefaultSource$$anonfun$createRelation$1.apply(DefaultSource.scala:71)
  at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:43)
  at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:42)
  at scala.Option.getOrElse(Option.scala:121)
  at com.databricks.spark.xml.XmlRelation.<init>(XmlRelation.scala:41)
  at com.databricks.spark.xml.XmlRelation$.apply(XmlRelation.scala:29)
  at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:74)
  at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:52)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  ... 45 elided `

**Comment by srowen** [comment]
This is some issue with your classpath, or mismatching Scala versions, etc. I'd make sure you have all the Hadoop dependencies in the app classpath and that they match, and that you check you're using the right Scala 2.11 vs 2.12 artifact. You may be missing another JAR file here, like the aws SDK or something.

**Comment by pankajwynk** [comment]
Thanks for instant reply. Zeppelin dependency issue. Closing this issues
