### ISSUE TITLE
XSD types not parsed correctly in some cased in XSDToSchema + XSD attributes ignored in some cases

### ISSUE THREAD

**Issue by miku872** [databricks/spark-xml#474]

**Comment by srowen** [comment]
Erm, context? what line number, how do you reproduce, etc?

**Comment by miku872** [comment]
Hi, I was trying to get schema from xsd file using XSDToSchema.read() method.
This is my xsd file

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="product">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="catalog_item" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="item_number"/>
                    <xs:element type="xs:float" name="price"/>
                    <xs:element name="size" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="color_swatch" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="image" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="description" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="gender" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="description"/>
            <xs:attribute type="xs:string" name="product_image"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

I'm getting error as follows 


scala.MatchError: null

	at com.databricks.spark.xml.util.XSDToSchema$.com$databricks$spark$xml$util$XSDToSchema$$getStructField(XSDToSchema.scala:73)
	at com.databricks.spark.xml.util.XSDToSchema$.com$databricks$spark$xml$util$XSDToSchema$$getStructField(XSDToSchema.scala:123)
	at com.databricks.spark.xml.util.XSDToSchema$$anonfun$6.apply(XSDToSchema.scala:171)
	at com.databricks.spark.xml.util.XSDToSchema$$anonfun$6.apply(XSDToSchema.scala:170)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.databricks.spark.xml.util.XSDToSchema$.com$databricks$spark$xml$util$XSDToSchema$$getStructField(XSDToSchema.scala:170)
	at com.databricks.spark.xml.util.XSDToSchema$$anonfun$6.apply(XSDToSchema.scala:171)
	at com.databricks.spark.xml.util.XSDToSchema$$anonfun$6.apply(XSDToSchema.scala:170)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.databricks.spark.xml.util.XSDToSchema$.com$databricks$spark$xml$util$XSDToSchema$$getStructField(XSDToSchema.scala:170)
	at com.databricks.spark.xml.util.XSDToSchema$$anonfun$6.apply(XSDToSchema.scala:171)
	at com.databricks.spark.xml.util.XSDToSchema$$anonfun$6.apply(XSDToSchema.scala:170)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.databricks.spark.xml.util.XSDToSchema$.com$databricks$spark$xml$util$XSDToSchema$$getStructField(XSDToSchema.scala:170)
	at com.databricks.spark.xml.util.XSDToSchema$$anonfun$6.apply(XSDToSchema.scala:171)
	at com.databricks.spark.xml.util.XSDToSchema$$anonfun$6.apply(XSDToSchema.scala:170)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.databricks.spark.xml.util.XSDToSchema$.com$databricks$spark$xml$util$XSDToSchema$$getStructField(XSDToSchema.scala:170)
	at com.databricks.spark.xml.util.XSDToSchema$.getStructType(XSDToSchema.scala:193)
	at com.databricks.spark.xml.util.XSDToSchema$.read(XSDToSchema.scala:47)
	at com.databricks.spark.xml.util.XSDToSchema$.read(XSDToSchema.scala:57)
	at com.databricks.spark.xml.util.XSDToSchema.read(XSDToSchema.scala)
	at com.databricks.spark.xml.JavaXmlSuite.testSave(JavaXmlSuite.java:85)

**Comment by srowen** [comment]
Got it, yeah that's a bug. There are two actually. One is that it was not looking up schema types correctly. The other is that it ignores attributes in several cases. I can fix both.

Can I use your XSD as a test case in the code?

**Comment by miku872** [comment]
sure, you can use it.
