### ISSUE TITLE
method getStructField(xmlSchema: XmlSchema, schemaType: XmlSchemaType) in XSDToSchema.scala isn't handling a particular case in its switch statements

### ISSUE THREAD

**Issue by miku872** [databricks/spark-xml#477]
I am trying to convert an xsd to schema where it calls the method getStructField(xmlSchema: XmlSchema, schemaType: XmlSchemaType) - here in my case schemaType is XmlSchemaComplexType hence it gets to line no. 119 to get a match for ContentModel. Now in my case ContentModel is of type XmlSchemaComplexContent which is not handled. Hence, it throws error 

`scala.MatchError: org.apache.ws.commons.schema.XmlSchemaComplexContent@5dc769f9 (of class org.apache.ws.commons.schema.XmlSchemaComplexContent)

	at com.databricks.spark.xml.util.XSDToSchema$.com$databricks$spark$xml$util$XSDToSchema$$getStructField(XSDToSchema.scala:118)
	at com.databricks.spark.xml.util.XSDToSchema$.getStructType(XSDToSchema.scala:200)
	at com.databricks.spark.xml.util.XSDToSchema$.read(XSDToSchema.scala:47)
	at com.databricks.spark.xml.util.XSDToSchema$.read(XSDToSchema.scala:57)
	at com.databricks.spark.xml.util.XSDToSchema.read(XSDToSchema.scala)`

**Comment by srowen** [comment]
Yeah, support for XSDs is definitely not complete. Can you share an example of the XSD? not sure how hard it is to add support for this.
