### ISSUE TITLE
Cannot work out spark-xml on aws

### ISSUE THREAD

**Issue by pratikwatwani** [databricks/spark-xml#488]
I am using an AWS cluster setup, with
Scala : 2.11.12
Spark : 2.4.3

I downloaded spark-xml_2.12-0.10.0.jar and moved the jar file to the spark installation /jar directory and also passed it via spark-submit command:
`spark-submit --packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.7,org.postgresql:postgresql:42.2.6 --jars spark-xml_2.12-0.10.0.jar`

However, I keep receiving this error:

20/09/30 20:32:31 INFO SharedState: Warehouse path is 'file:/home/ubuntu/spark-warehouse'.
20/09/30 20:32:32 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
Traceback (most recent call last):
  File "/home/ubuntu/t.py", line 14, in <module>
    lines = spark.read.format('xml').option('rowTag','record').load(sys.argv[1])
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 166, in load
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o33.load.
: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcD$sp
	at com.databricks.spark.xml.XmlOptions.<init>(XmlOptions.scala:36)
	at com.databricks.spark.xml.XmlOptions$.apply(XmlOptions.scala:66)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:66)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:52)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcD$sp
	... 19 more
Caused by: java.lang.ClassNotFoundException: scala.runtime.java8.JFunction0$mcD$sp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 19 more

Any suggestions how to sort this?

**Comment by srowen** [comment]
You are running Scala 2.11, but you tried to use the Scala 2.12 version of the library. Use the `_2.11` artifact.

**Comment by pratikwatwani** [comment]
I tried with spark-xml_2.11:0.6.0, but I receive the same error

**Comment by srowen** [comment]
If you also put the 2.12 build in the Spark distro, that's also the problem. You just need to supply it once. This is definitely a scala version mismatch.

**Comment by pratikwatwani** [comment]
No, I made sure to not have both jars, I just have spark-xml_2.11:0.6.0 in the installation jars directory, and my spark-submit is this: 
spark-submit --packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.7,org.postgresql:postgresql:42.2.6,com.databricks:spark-xml_2.11:0.6.0

Since this didn't work, I used the alternative:
spark-submit --packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.7,org.postgresql:postgresql:42.2.6 --jars spark-xml_2.11:0.6.0.jar
but this failed too
