### ISSUE TITLE
Unable to infer long datatype when xml is processed using xsd file

### ISSUE THREAD

**Issue by pavanguru423** [databricks/spark-xml#520]
When we specify the xsd with long data type for an xml attribute, it is inferred as integer type and throws NumberFormatException at runtime.
Below are my xml and xsd files:
XML:
----
```
<?xml version="1.0"?>
<test>
    <userId>1051132950001251</userId>
</test>
```

XSD
-----
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="test">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:long" name="userId"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

Code
-----
```
val df = spark.read.option("wholetext","true").text("src/main/resources/test.xml")
val schema = XSDToSchema.read(Paths.get("src/main/resources/test.xsd"))
println(schema)
val options = Map[String, String](("mode","FAILFAST"))
val parsed = df.withColumn("parsed", from_xml(col("value"), schema(0).dataType,options))
parsed.show(false)
```

Exception StackTrace
--------------------
Caused by: java.lang.NumberFormatException: For input string: "1051132950001251"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:583)
    at java.lang.Integer.parseInt(Integer.java:615)
    at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:273)
    at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
    at com.databricks.spark.xml.util.TypeCast$.castTo(TypeCast.scala:59)
    at com.databricks.spark.xml.util.TypeCast$.signSafeToInt(TypeCast.scala:238)
    at com.databricks.spark.xml.util.TypeCast$.convertTo(TypeCast.scala:155)
    at com.databricks.spark.xml.parsers.StaxXmlParser$.convertField(StaxXmlParser.scala:192)
    at com.databricks.spark.xml.parsers.StaxXmlParser$.convertObject(StaxXmlParser.scala:334)
    at com.databricks.spark.xml.parsers.StaxXmlParser$.com$databricks$spark$xml$parsers$StaxXmlParser$$doParseColumn(StaxXmlParser.scala:85)
    ... 25 more

**Comment by srowen** [comment]
Sounds like a bug. I'll look into it.

**Comment by srowen** [comment]
Resolved by https://github.com/databricks/spark-xml/pull/522
