### ISSUE TITLE
XML read error - Py4JJavaError: An error occurred while calling o632.load

### ISSUE THREAD

**Issue by mohammedumar08** [databricks/spark-xml#550]
Hi,

I am trying to read xml file from Azure Data Lake Gen 2 using Databricks.

Databricks Versions Setup:
Spark - 2.4.3
Scala - 2.11
Python - 3
spark-xml - HyukjinKwon:spark-xml:0.1.1-s_2.11 installed on the Databricks Cluster

Code Used:

from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

file_location = "abfss://_containername_@_storageaccountname_.dfs.core.windows.net/books.xml"

df = spark.read.format('xml').options(rowTag='book',rootTag='books').load(file_location)

**Error:**
Py4JJavaError                             Traceback (most recent call last)
<command-647486008107174> in <module>()
----> 1 df = spark.read.format('xml').options(rowTag='book',rootTag='books').load(file_location)

/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    164         self.options(**options)
    165         if isinstance(path, basestring):
--> 166             return self._df(self._jreader.load(path))
    167         elif path is not None:
    168             if type(path) != list:

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o632.load.
: Failure to initialize configuration
	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.services.SimpleKeyProvider.getStorageAccountKey(SimpleKeyProvider.java:51)
	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.AbfsConfiguration.getStorageAccountKey(AbfsConfiguration.java:382)
	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.initializeClient(AzureBlobFileSystemStore.java:1095)
	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.<init>(AzureBlobFileSystemStore.java:152)
	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.initialize(AzureBlobFileSystem.java:137)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.setInputPaths(FileInputFormat.java:500)
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.setInputPaths(FileInputFormat.java:469)
	at org.apache.spark.SparkContext$$anonfun$newAPIHadoopFile$2.apply(SparkContext.scala:1278)
	at org.apache.spark.SparkContext$$anonfun$newAPIHadoopFile$2.apply(SparkContext.scala:1266)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.SparkContext.withScope(SparkContext.scala:817)
	at org.apache.spark.SparkContext.newAPIHadoopFile(SparkContext.scala:1266)
	at org.apache.spark.sql.xml.util.XmlFile$.withCharset(XmlFile.scala:35)
	at org.apache.spark.sql.xml.DefaultSource$$anonfun$createRelation$1.apply(DefaultSource.scala:87)
	at org.apache.spark.sql.xml.DefaultSource$$anonfun$createRelation$1.apply(DefaultSource.scala:87)
	at org.apache.spark.sql.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:59)
	at org.apache.spark.sql.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:57)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.xml.XmlRelation.<init>(XmlRelation.scala:56)
	at org.apache.spark.sql.xml.DefaultSource.createRelation(DefaultSource.scala:93)
	at org.apache.spark.sql.xml.DefaultSource.createRelation(DefaultSource.scala:43)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:347)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:307)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:293)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

Please help where I am doing wrong here.

Thanks in advance!!

**Comment by srowen** [comment]
Look at the stack trace - it's an error related to authenticating to access Azure Blob Storage. Not related to this project

**Comment by mohammedumar08** [comment]
Hi Sean,

I can read any csv file from Azure Data Lake Gen 2 using Databricks but not the xml file. It uses same storageaccount and container.

Could you please let know where I need to check. Thanks!!
